### ISSUE TITLE
An error 

### ISSUE THREAD

**Issue by BlockBoi19** [RoturTW/main#4]
There is a error where login fails, could you fix it

**Comment by Mistium** [comment]
can you explain what the issue is further?

**Comment by Mistium** [comment]
looks a lot like you just tried to use rotur on an non whitelisted system, which is kinda the point in order to stop randoms from instantly being able to access rotur. Join the origin and the rotur discord servers so that i can guide you through using it https://discord.gg/7DcwkqrZ9S

**Comment by BlockBoi19** [comment]
Why not here, you could tell me here

**Comment by BlockBoi19** [comment]
Do I need to register first or login first

**Comment by Mistium** [comment]
> Do I need to register first or login first

neither, you are connected on a non-whitelisted system

**Comment by Mistium** [comment]
the server will reject you since the os you have told it you are connected on is invalid, thats why i want you to join discord so i can explain this to you in more detail and depth while actually being able to answer questions in real time instead of waiting like 3-4 hours per response

**Comment by BlockBoi19** [comment]
I can't get on discord unfortunately

**Comment by Mistium** [comment]
ah. well rotur is designed for making turbowarp operating systems, so unless you are doing that, it's probably not the best thing to use for your project.

**Comment by BlockBoi19** [comment]
Oh... guess I'll use cloud link instead

**Comment by Mistium** [comment]
Alrighty lmao 👍🏻
